"""extracted events

Revision ID: 0fb7f81e7446
Revises: fca30d40650b
Create Date: 2026-10-07 15:04:26.485668
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0fb7f81e7446'
down_revision: str | None = 'fca30d40650b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('routed_through', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'document_id', 'ordinal')
    )
    op.create_index(op.f('ix_extracted_events_concept_id'), 'extracted_events', ['concept_id'], unique=False)
    op.create_index(op.f('ix_extracted_events_outcome'), 'extracted_events', ['outcome'], unique=False)
    op.create_index(op.f('ix_extracted_events_document_id'), 'extracted_events', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_events_run_id'), 'extracted_events', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_events_run_id'), table_name='extracted_events')
    op.drop_index(op.f('ix_extracted_events_document_id'), table_name='extracted_events')
    op.drop_index(op.f('ix_extracted_events_concept_id'), table_name='extracted_events')
    op.drop_index(op.f('ix_extracted_events_outcome'), table_name='extracted_events')
    op.drop_table('extracted_events')
    # ### end Alembic commands ###
