"""document duplicate_of

Revision ID: 1126be49cdc0
Revises: 8252090b7d06
Create Date: 2026-10-05 23:02:01.282383
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1126be49cdc0'
down_revision: str | None = '8252090b7d06'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('duplicate_of', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_duplicate_of'), 'documents', ['duplicate_of'], unique=False)
    op.create_foreign_key(None, 'documents', 'documents', ['duplicate_of'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_duplicate_of'), table_name='documents')
    op.drop_column('documents', 'duplicate_of')
    # ### end Alembic commands ###
