"""machine annotations

Revision ID: 12015d90a306
Revises: 4bb037c08f53
Create Date: 2026-10-08 19:33:43.260608
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '12015d90a306'
down_revision: str | None = '4bb037c08f53'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ontology_id', 'name')
    )
    op.create_index(op.f('ix_annotation_sets_ontology_id'), 'annotation_sets', ['ontology_id'], unique=False)
    op.create_table('machine_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ontology_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['annotation_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_id', 'document_id', 'concept_id')
    )
    op.create_index(op.f('ix_machine_annotations_concept_id'), 'machine_annotations', ['concept_id'], unique=False)
    op.create_index(op.f('ix_machine_annotations_document_id'), 'machine_annotations', ['document_id'], unique=False)
    op.create_index(op.f('ix_machine_annotations_set_id'), 'machine_annotations', ['set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machine_annotations_set_id'), table_name='machine_annotations')
    op.drop_index(op.f('ix_machine_annotations_document_id'), table_name='machine_annotations')
    op.drop_index(op.f('ix_machine_annotations_concept_id'), table_name='machine_annotations')
    op.drop_table('machine_annotations')
    op.drop_index(op.f('ix_annotation_sets_ontology_id'), table_name='annotation_sets')
    op.drop_table('annotation_sets')
    # ### end Alembic commands ###
