"""initial schema

Revision ID: 28bf03246c75
Revises: 
Create Date: 2026-08-26 21:34:32.875060
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy
revision: str = '28bf03246c75'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body_path', sa.Text(), nullable=True),
    sa.Column('body_chars', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('extractor', sa.String(), nullable=True),
    sa.Column('extractor_version', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('is_junk', sa.Boolean(), nullable=False),
    sa.Column('junk_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_documents_is_junk'), 'documents', ['is_junk'], unique=False)
    op.create_index(op.f('ix_documents_url_hash'), 'documents', ['url_hash'], unique=True)
    op.create_table('embedding_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('dim', sa.Integer(), nullable=True),
    sa.Column('normalized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('feed_slices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed', sa.String(), nullable=False),
    sa.Column('slice_key', sa.String(), nullable=False),
    sa.Column('sliced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rows_in_feed', sa.Integer(), nullable=False),
    sa.Column('rows_matched', sa.Integer(), nullable=False),
    sa.Column('documents_new', sa.Integer(), nullable=False),
    sa.Column('documents_cached', sa.Integer(), nullable=False),
    sa.Column('documents_failed', sa.Integer(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed', 'slice_key')
    )
    op.create_index(op.f('ix_feed_slices_feed'), 'feed_slices', ['feed'], unique=False)
    op.create_index(op.f('ix_feed_slices_slice_key'), 'feed_slices', ['slice_key'], unique=False)
    op.create_index(op.f('ix_feed_slices_sliced_at'), 'feed_slices', ['sliced_at'], unique=False)
    op.create_index(op.f('ix_feed_slices_status'), 'feed_slices', ['status'], unique=False)
    op.create_table('ingest_watermarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed', sa.String(), nullable=False),
    sa.Column('last_slice_key', sa.String(), nullable=True),
    sa.Column('last_sliced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed')
    )
    op.create_table('loci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=True),
    sa.Column('fips', sa.String(length=2), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso3')
    )
    op.create_index(op.f('ix_loci_fips'), 'loci', ['fips'], unique=False)
    op.create_index(op.f('ix_loci_iso2'), 'loci', ['iso2'], unique=False)
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('parent_code_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_code_id'], ['codes.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['code_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'code')
    )
    op.create_index(op.f('ix_codes_code'), 'codes', ['code'], unique=False)
    op.create_index(op.f('ix_codes_level'), 'codes', ['level'], unique=False)
    op.create_index(op.f('ix_codes_system_id'), 'codes', ['system_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('text_key', sa.String(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['embedding_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'object_type', 'object_id', 'text_key')
    )
    op.create_index(op.f('ix_embeddings_model_id'), 'embeddings', ['model_id'], unique=False)
    op.create_index(op.f('ix_embeddings_object_id'), 'embeddings', ['object_id'], unique=False)
    op.create_index(op.f('ix_embeddings_object_type'), 'embeddings', ['object_type'], unique=False)
    op.create_index(op.f('ix_embeddings_text_key'), 'embeddings', ['text_key'], unique=False)
    op.create_table('feed_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slice_id', sa.Integer(), nullable=False),
    sa.Column('feed_event_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('event_code', sa.String(), nullable=True),
    sa.Column('base_code', sa.String(), nullable=True),
    sa.Column('root_code', sa.String(), nullable=True),
    sa.Column('locus_id', sa.Integer(), nullable=True),
    sa.Column('occurred_on', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['locus_id'], ['loci.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slice_id'], ['feed_slices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slice_id', 'feed_event_id')
    )
    op.create_index(op.f('ix_feed_events_base_code'), 'feed_events', ['base_code'], unique=False)
    op.create_index(op.f('ix_feed_events_document_id'), 'feed_events', ['document_id'], unique=False)
    op.create_index(op.f('ix_feed_events_event_code'), 'feed_events', ['event_code'], unique=False)
    op.create_index(op.f('ix_feed_events_occurred_on'), 'feed_events', ['occurred_on'], unique=False)
    op.create_index(op.f('ix_feed_events_root_code'), 'feed_events', ['root_code'], unique=False)
    op.create_index(op.f('ix_feed_events_slice_id'), 'feed_events', ['slice_id'], unique=False)
    op.create_table('ontologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'slug')
    )
    op.create_index(op.f('ix_ontologies_owner_id'), 'ontologies', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ontologies_slug'), 'ontologies', ['slug'], unique=False)
    op.create_table('similarity_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('source_object_type', sa.String(), nullable=False),
    sa.Column('source_text_key', sa.String(), nullable=False),
    sa.Column('target_object_type', sa.String(), nullable=False),
    sa.Column('target_text_key', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['embedding_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ontology_id', 'name')
    )
    op.create_index(op.f('ix_categories_ontology_id'), 'categories', ['ontology_id'], unique=False)
    op.create_table('concept_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['concept_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_groups_ontology_id'), 'concept_groups', ['ontology_id'], unique=False)
    op.create_table('ontology_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('n_concepts', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ontology_id', 'content_hash'),
    sa.UniqueConstraint('ontology_id', 'version')
    )
    op.create_index(op.f('ix_ontology_snapshots_content_hash'), 'ontology_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_ontology_snapshots_ontology_id'), 'ontology_snapshots', ['ontology_id'], unique=False)
    op.create_index(op.f('ix_ontology_snapshots_version'), 'ontology_snapshots', ['version'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=False),
    sa.Column('ontology_version', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidates_key', sa.String(), nullable=False),
    sa.Column('judge_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('progress_done', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_candidates_key'), 'runs', ['candidates_key'], unique=False)
    op.create_index(op.f('ix_runs_judge_key'), 'runs', ['judge_key'], unique=False)
    op.create_index(op.f('ix_runs_ontology_id'), 'runs', ['ontology_id'], unique=False)
    op.create_index(op.f('ix_runs_ontology_version'), 'runs', ['ontology_version'], unique=False)
    op.create_index(op.f('ix_runs_owner_id'), 'runs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('similarity_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['similarity_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'source_id', 'target_id')
    )
    op.create_index(op.f('ix_similarity_scores_run_id'), 'similarity_scores', ['run_id'], unique=False)
    op.create_index(op.f('ix_similarity_scores_source_id'), 'similarity_scores', ['source_id'], unique=False)
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('inclusion_criteria', sa.Text(), nullable=True),
    sa.Column('exclusion_criteria', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ontology_id', 'name')
    )
    op.create_index(op.f('ix_concepts_ontology_id'), 'concepts', ['ontology_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('matched_code', sa.String(), nullable=True),
    sa.Column('matched_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'document_id', 'concept_id')
    )
    op.create_index(op.f('ix_candidates_concept_id'), 'candidates', ['concept_id'], unique=False)
    op.create_index(op.f('ix_candidates_document_id'), 'candidates', ['document_id'], unique=False)
    op.create_index(op.f('ix_candidates_run_id'), 'candidates', ['run_id'], unique=False)
    op.create_index(op.f('ix_candidates_selected'), 'candidates', ['selected'], unique=False)
    op.create_table('concept_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('similarity_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['similarity_run_id'], ['similarity_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id', 'code_id')
    )
    op.create_index(op.f('ix_concept_codes_code_id'), 'concept_codes', ['code_id'], unique=False)
    op.create_index(op.f('ix_concept_codes_concept_id'), 'concept_codes', ['concept_id'], unique=False)
    op.create_index(op.f('ix_concept_codes_similarity_run_id'), 'concept_codes', ['similarity_run_id'], unique=False)
    op.create_table('concept_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['concept_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'concept_id')
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('locus_id', sa.Integer(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locus_id'], ['loci.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id', 'locus_id', 'occurred_on')
    )
    op.create_index(op.f('ix_observations_concept_id'), 'observations', ['concept_id'], unique=False)
    op.create_index(op.f('ix_observations_locus_id'), 'observations', ['locus_id'], unique=False)
    op.create_index(op.f('ix_observations_occurred_on'), 'observations', ['occurred_on'], unique=False)
    op.create_table('pair_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('locus_id', sa.Integer(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('proposed_by', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ontology_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locus_id'], ['loci.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'concept_id')
    )
    op.create_index(op.f('ix_pair_labels_concept_id'), 'pair_labels', ['concept_id'], unique=False)
    op.create_index(op.f('ix_pair_labels_document_id'), 'pair_labels', ['document_id'], unique=False)
    op.create_index(op.f('ix_pair_labels_occurred_on'), 'pair_labels', ['occurred_on'], unique=False)
    op.create_index(op.f('ix_pair_labels_ontology_version'), 'pair_labels', ['ontology_version'], unique=False)
    op.create_index(op.f('ix_pair_labels_source'), 'pair_labels', ['source'], unique=False)
    op.create_table('verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('vote_fraction', sa.Float(), nullable=True),
    sa.Column('locus_id', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_id', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('latency_s', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locus_id'], ['loci.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'document_id', 'concept_id')
    )
    op.create_index(op.f('ix_verdicts_concept_id'), 'verdicts', ['concept_id'], unique=False)
    op.create_index(op.f('ix_verdicts_document_id'), 'verdicts', ['document_id'], unique=False)
    op.create_index(op.f('ix_verdicts_matched'), 'verdicts', ['matched'], unique=False)
    op.create_index(op.f('ix_verdicts_prompt_id'), 'verdicts', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_verdicts_run_id'), 'verdicts', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verdicts_run_id'), table_name='verdicts')
    op.drop_index(op.f('ix_verdicts_prompt_id'), table_name='verdicts')
    op.drop_index(op.f('ix_verdicts_matched'), table_name='verdicts')
    op.drop_index(op.f('ix_verdicts_document_id'), table_name='verdicts')
    op.drop_index(op.f('ix_verdicts_concept_id'), table_name='verdicts')
    op.drop_table('verdicts')
    op.drop_index(op.f('ix_pair_labels_source'), table_name='pair_labels')
    op.drop_index(op.f('ix_pair_labels_ontology_version'), table_name='pair_labels')
    op.drop_index(op.f('ix_pair_labels_occurred_on'), table_name='pair_labels')
    op.drop_index(op.f('ix_pair_labels_document_id'), table_name='pair_labels')
    op.drop_index(op.f('ix_pair_labels_concept_id'), table_name='pair_labels')
    op.drop_table('pair_labels')
    op.drop_index(op.f('ix_observations_occurred_on'), table_name='observations')
    op.drop_index(op.f('ix_observations_locus_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_concept_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_table('concept_group_members')
    op.drop_index(op.f('ix_concept_codes_similarity_run_id'), table_name='concept_codes')
    op.drop_index(op.f('ix_concept_codes_concept_id'), table_name='concept_codes')
    op.drop_index(op.f('ix_concept_codes_code_id'), table_name='concept_codes')
    op.drop_table('concept_codes')
    op.drop_index(op.f('ix_candidates_selected'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_run_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_document_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_concept_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_concepts_ontology_id'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_similarity_scores_source_id'), table_name='similarity_scores')
    op.drop_index(op.f('ix_similarity_scores_run_id'), table_name='similarity_scores')
    op.drop_table('similarity_scores')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_owner_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_ontology_version'), table_name='runs')
    op.drop_index(op.f('ix_runs_ontology_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_judge_key'), table_name='runs')
    op.drop_index(op.f('ix_runs_candidates_key'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_ontology_snapshots_version'), table_name='ontology_snapshots')
    op.drop_index(op.f('ix_ontology_snapshots_ontology_id'), table_name='ontology_snapshots')
    op.drop_index(op.f('ix_ontology_snapshots_content_hash'), table_name='ontology_snapshots')
    op.drop_table('ontology_snapshots')
    op.drop_index(op.f('ix_concept_groups_ontology_id'), table_name='concept_groups')
    op.drop_table('concept_groups')
    op.drop_index(op.f('ix_categories_ontology_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('similarity_runs')
    op.drop_index(op.f('ix_ontologies_slug'), table_name='ontologies')
    op.drop_index(op.f('ix_ontologies_owner_id'), table_name='ontologies')
    op.drop_table('ontologies')
    op.drop_index(op.f('ix_feed_events_slice_id'), table_name='feed_events')
    op.drop_index(op.f('ix_feed_events_root_code'), table_name='feed_events')
    op.drop_index(op.f('ix_feed_events_occurred_on'), table_name='feed_events')
    op.drop_index(op.f('ix_feed_events_event_code'), table_name='feed_events')
    op.drop_index(op.f('ix_feed_events_document_id'), table_name='feed_events')
    op.drop_index(op.f('ix_feed_events_base_code'), table_name='feed_events')
    op.drop_table('feed_events')
    op.drop_index(op.f('ix_embeddings_text_key'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_object_type'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_object_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_model_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_codes_system_id'), table_name='codes')
    op.drop_index(op.f('ix_codes_level'), table_name='codes')
    op.drop_index(op.f('ix_codes_code'), table_name='codes')
    op.drop_table('codes')
    op.drop_table('owners')
    op.drop_index(op.f('ix_loci_iso2'), table_name='loci')
    op.drop_index(op.f('ix_loci_fips'), table_name='loci')
    op.drop_table('loci')
    op.drop_table('ingest_watermarks')
    op.drop_index(op.f('ix_feed_slices_status'), table_name='feed_slices')
    op.drop_index(op.f('ix_feed_slices_sliced_at'), table_name='feed_slices')
    op.drop_index(op.f('ix_feed_slices_slice_key'), table_name='feed_slices')
    op.drop_index(op.f('ix_feed_slices_feed'), table_name='feed_slices')
    op.drop_table('feed_slices')
    op.drop_table('embedding_models')
    op.drop_index(op.f('ix_documents_url_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_junk'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('code_systems')
    # ### end Alembic commands ###
