"""link snapshots

Revision ID: 4bb037c08f53
Revises: 0fb7f81e7446
Create Date: 2026-10-08 19:01:46.930469
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '4bb037c08f53'
down_revision: str | None = '0fb7f81e7446'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('n_links', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ontology_id', 'content_hash'),
    sa.UniqueConstraint('ontology_id', 'version')
    )
    op.create_index(op.f('ix_link_snapshots_content_hash'), 'link_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_link_snapshots_ontology_id'), 'link_snapshots', ['ontology_id'], unique=False)
    op.create_index(op.f('ix_link_snapshots_version'), 'link_snapshots', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_snapshots_version'), table_name='link_snapshots')
    op.drop_index(op.f('ix_link_snapshots_ontology_id'), table_name='link_snapshots')
    op.drop_index(op.f('ix_link_snapshots_content_hash'), table_name='link_snapshots')
    op.drop_table('link_snapshots')
    # ### end Alembic commands ###
