"""gkg articles and slice scope

Revision ID: 8252090b7d06
Revises: 28bf03246c75
Create Date: 2026-10-05 22:33:57.666965
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '8252090b7d06'
down_revision: str | None = '28bf03246c75'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slice_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('themes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('locus_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slice_id'], ['feed_slices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slice_id', 'record_id')
    )
    op.create_index(op.f('ix_feed_articles_document_id'), 'feed_articles', ['document_id'], unique=False)
    op.create_index('ix_feed_articles_locus_ids', 'feed_articles', ['locus_ids'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_feed_articles_published_at'), 'feed_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_feed_articles_slice_id'), 'feed_articles', ['slice_id'], unique=False)
    op.create_index('ix_feed_articles_themes', 'feed_articles', ['themes'], unique=False, postgresql_using='gin')
    op.add_column('feed_slices', sa.Column('scope', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_slices', 'scope')
    op.drop_index('ix_feed_articles_themes', table_name='feed_articles', postgresql_using='gin')
    op.drop_index(op.f('ix_feed_articles_slice_id'), table_name='feed_articles')
    op.drop_index(op.f('ix_feed_articles_published_at'), table_name='feed_articles')
    op.drop_index('ix_feed_articles_locus_ids', table_name='feed_articles', postgresql_using='gin')
    op.drop_index(op.f('ix_feed_articles_document_id'), table_name='feed_articles')
    op.drop_table('feed_articles')
    # ### end Alembic commands ###
