"""concept relations and snapshot edges

Revision ID: b0f801e569c8
Revises: dabacec1fe24
Create Date: 2026-10-06 18:40:58.700094
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b0f801e569c8'
down_revision: str | None = 'dabacec1fe24'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ontology_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('predicate', sa.String(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("predicate IN ('subclass_of', 'precursor_of')", name='ck_concept_relations_predicate'),
    sa.CheckConstraint('subject_id <> object_id', name='ck_concept_relations_not_self'),
    sa.ForeignKeyConstraint(['object_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ontology_id'], ['ontologies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'predicate', 'object_id')
    )
    op.create_index(op.f('ix_concept_relations_object_id'), 'concept_relations', ['object_id'], unique=False)
    op.create_index(op.f('ix_concept_relations_ontology_id'), 'concept_relations', ['ontology_id'], unique=False)
    op.create_index(op.f('ix_concept_relations_subject_id'), 'concept_relations', ['subject_id'], unique=False)
    op.add_column('ontology_snapshots', sa.Column('edges', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ontology_snapshots', 'edges')
    op.drop_index(op.f('ix_concept_relations_subject_id'), table_name='concept_relations')
    op.drop_index(op.f('ix_concept_relations_ontology_id'), table_name='concept_relations')
    op.drop_index(op.f('ix_concept_relations_object_id'), table_name='concept_relations')
    op.drop_table('concept_relations')
    # ### end Alembic commands ###
