"""calendar reviews

Revision ID: dabacec1fe24
Revises: 1126be49cdc0
Create Date: 2026-10-06 17:44:24.298450
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'dabacec1fe24'
down_revision: str | None = '1126be49cdc0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.String(), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'document_url')
    )
    op.create_index(op.f('ix_calendar_reviews_entry_id'), 'calendar_reviews', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_reviews_entry_id'), table_name='calendar_reviews')
    op.drop_table('calendar_reviews')
    # ### end Alembic commands ###
